# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run UI Tests"
  lane :run_ui_tests do
    scan(
      scheme: "SafariOpener",
      devices: [], # Clear the devices array to avoid conflicts with the destination parameter
      destination: "platform=iOS Simulator,name=iPhone 11,OS=17.2", # Specify the simulator and OS version
      clean: true
    )
  end
end
