default_platform(:ios)

platform :ios do
  desc "Run UI Tests"
  lane :run_ui_tests do
    scan(
      scheme: "SafariOpener",
      devices: [], # Clear the devices array to avoid conflicts with the destination parameter
      destination: "id=B13460AD-AB89-487A-B342-2977DF298BEB",
      clean: true,
      output_directory: "./fastlane/test_output",
      output_types: "html,junit",
      buildlog_path: "~/Library/Logs/scan"
    )
  end
end
