default_platform(:ios)

platform :ios do
  desc "Run UI Tests"
  lane :run_ui_tests do
    scan(
      scheme: "SafariOpener",
      project: "SafariOpener.xcodeproj",
      devices: [], # Clear the devices array to avoid conflicts with the destination parameter
      destination: "id=7B9194BE-A1C4-4895-9332-459BD67773D1",
      clean: true,
      output_directory: "./fastlane/test_output",
      output_types: "html,junit",
      buildlog_path: "~/Library/Logs/scan"
    )
  end
end
